<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Covid Cases</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/yeti.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 45px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 50px;
  margin-top: -50px;
}
.section h2 {
  padding-top: 50px;
  margin-top: -50px;
}
.section h3 {
  padding-top: 50px;
  margin-top: -50px;
}
.section h4 {
  padding-top: 50px;
  margin-top: -50px;
}
.section h5 {
  padding-top: 50px;
  margin-top: -50px;
}
.section h6 {
  padding-top: 50px;
  margin-top: -50px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Personal Page</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="QuinticPoly.html">Quintic Polynomials</a>
</li>
<li>
  <a href="CompTheoryLang.html">Computer Theory and Languages</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    R Samples
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="RandomVariables.html">Random Variables</a>
    </li>
    <li>
      <a href="IntroDataFrame.html">Intro to Data Frame</a>
    </li>
    <li>
      <a href="AnalyzingSimulations.html">Analyzing Simulations</a>
    </li>
    <li>
      <a href="PredictingFunction.html">Predicting Function</a>
    </li>
    <li>
      <a href="InterestRate.html">Interest Rate</a>
    </li>
    <li>
      <a href="CovidCases.html">Covid Cases</a>
    </li>
    <li>
      <a href="GroceriesProject.html">Groceries Data</a>
    </li>
  </ul>
</li>
<li>
  <a href="sqlSample.html">SQL Example</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Covid Cases</h1>

</div>


<div id="outcomes" class="section level4">
<h4>Outcomes</h4>
<ul>
<li>Download and load public data sets</li>
<li>Read and interpret metadata</li>
<li>Evaluate general claims using data, in the presence of missing data</li>
<li>Create and interpret interaction plots</li>
</ul>
</div>
<div id="instructions" class="section level4">
<h4>Instructions</h4>
<ul>
<li>Answer the following questions, and show all your R code.</li>
<li>Upload your submission to Canvas in nicely formatted HTML generated from Rstudio.</li>
</ul>
<p>Download the <a href="https://data.cdc.gov/Case-Surveillance/COVID-19-Case-Surveillance-Public-Use-Data/vbim-akqf">COVID-19 Case Surveillance Public Use Data</a> from the US Center for Disease Control (CDC). Click on the “Export” button in the top right corner next to download the actual data set.</p>
<p><em>Hint: It might be useful to create a new numeric column for severity based on the values of the <code>hosp, icu, death</code> columns. If you do this, make sure you explain the meaning and rationale behind your choices.</em></p>
</div>
<div id="questions" class="section level1">
<h1>Questions</h1>
<div id="reading-the-documentation" class="section level2">
<h2>1 - Reading the Documentation</h2>
<p><em>a) Describe this data set at a high level. What does each row represent?</em></p>
<p>This data set includes COVID-19 cases reported in US with date, medical condition data, ICU data, number of deaths, sex, age groups, race and ethnicity, etc. Each row represents each case reported.</p>
<p><em>b) How many rows and columns do you expect to see based on the website? Load the data into R. Is this reflected in the data?</em></p>
<pre class="r"><code>covid = read.csv(&quot;C:/Users/kanni/Downloads/COVID-19_Case_Surveillance_Public_Use_Data.csv&quot;)
dim(covid)</code></pre>
<pre><code>## [1] 4481062      11</code></pre>
<p>There are 4481062 rows and 11 columns in the data.</p>
</div>
<div id="missing-data" class="section level2">
<h2>2 - Missing Data</h2>
<p><em>There are few <code>NA</code> values in this data, but much of the data is missing, unknown, or blank. Which columns have the highest proportion of missing data? Why might these be missing?</em></p>
<pre class="r"><code>missing_count = colSums(is.na(covid) | covid == &quot;Missing&quot; | covid == &quot;Unknown&quot;)
missing_count</code></pre>
<pre><code>##              ï..cdc_report_dt                   pos_spec_dt 
##                             0                             0 
##                      onset_dt                current_status 
##                             0                             0 
##                           sex                     age_group 
##                         54045                          5281 
## Race.and.ethnicity..combined.                       hosp_yn 
##                       1895805                       2138483 
##                        icu_yn                      death_yn 
##                       3932347                       2269410 
##                    medcond_yn 
##                       3536092</code></pre>
<p>Counting all <code>NA</code> values which includes missing, unknown, the column with highest counts is icu_yn with 3,932,347 <code>NA</code> values. These data might be missing as patients are still under care for COVID, but haven’t yet to be in ICU.</p>
</div>
<div id="age-risk" class="section level2">
<h2>3 - Age Risk</h2>
<p><em>The <a href="https://www.cdc.gov/coronavirus/2019-ncov/need-extra-precautions/older-adults.html">CDC states</a> “Among adults, the risk for severe illness from COVID-19 increases with age, with older adults at highest risk.” Does the data support this claim?</em></p>
<p><em>Hint 1: It might be useful to think about these COVID illness rates by age after adjusting for the relative sizes of each age group in the country. You’ll need to bring in another data source to do this.</em></p>
<pre class="r"><code>severity = rep(0, times = nrow(covid))
severity[covid$hosp_yn == &quot;Yes&quot;] = 1
severity[covid$icu_yn == &quot;Yes&quot;] = 2
severity[covid$death_yn == &quot;Yes&quot;] = 3
covid$severity = severity

table(covid$age_group)</code></pre>
<pre><code>## 
##   0 - 9 Years 10 - 19 Years 20 - 29 Years 30 - 39 Years 40 - 49 Years 
##        140213        386579        869057        748175        694670 
## 50 - 59 Years 60 - 69 Years 70 - 79 Years     80+ Years       Unknown 
##        671827        468486        263186        233588          5188</code></pre>
<pre class="r"><code>Age_Severe_Plot = table(covid[, c(&quot;age_group&quot;, &quot;severity&quot;)])
plot(table(covid$age_group),main = &quot;Confirmed Cases by Age Groups&quot;, xlab = &quot;Age Groups&quot;, ylab =&quot;Confirmed Cases&quot;)</code></pre>
<p><img src="CovidCases_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<pre class="r"><code>plot(Age_Severe_Plot,main = &quot;Severe Cases by Age Groups&quot;,xlab=&quot;Age Groups&quot;,ylab=&quot;Severity Level&quot;)</code></pre>
<p><img src="CovidCases_files/figure-html/unnamed-chunk-3-2.png" width="672" /></p>
<p>For severity, I select <code>hosp_yn</code> as first level of severe illness, <code>icu_yn</code> as second level, <code>death_yn</code> as third level, and the rest as no severe illness. The table shows the number of cases at first, second, third level of severe illness increase with the ages groups. Also, cases with no severe illness decrease with the age groups.</p>
</div>
<div id="medical-condition-risk" class="section level2">
<h2>4 - Medical Condition Risk</h2>
<p><em>The <a href="https://www.cdc.gov/coronavirus/2019-ncov/need-extra-precautions/people-with-medical-conditions.html">CDC states</a> “People of any age with certain underlying medical conditions are at increased risk for severe illness from COVID-19” Does the data support this claim?</em></p>
<pre class="r"><code>table(covid$medcond_yn)</code></pre>
<pre><code>## 
## Missing      No Unknown     Yes 
## 2977430  377203  558662  567767</code></pre>
<pre class="r"><code>medcond_Severe_Plot = table(covid[, c(&quot;medcond_yn&quot;, &quot;severity&quot;)])
plot(table(covid$medcond_yn),main = &quot;Confirmed Cases with Pre-Medical Conditions&quot;, xlab = &quot;Pre-Medical Conditions&quot;, ylab =&quot;Confirmed Cases&quot;)</code></pre>
<p><img src="CovidCases_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<pre class="r"><code>plot(medcond_Severe_Plot,main = &quot;Severe Cases with Pre-Medical Conditions&quot;,xlab=&quot;Pre-Medical Conditions&quot;,ylab=&quot;Severity Level&quot;)</code></pre>
<p><img src="CovidCases_files/figure-html/unnamed-chunk-4-2.png" width="672" /></p>
<p>The table shows there are more cases at 1st-3rd level of severe illness among patients with pre-medical conditions. Also, there are more cases at no risk of severe illness among patients with no pre-medical conditions. This might not be enough to conclude patients with pre-medical conditions would be at a higher risk of severe illness. Besides, for <code>NA</code> values, it is still a relatively low number of cases at higher risk of severe illness.</p>
</div>
<div id="interaction-effects" class="section level2">
<h2>5 - Interaction Effects</h2>
<p><em>In statistics, an <strong>interaction effect</strong> is when two or more variables have a non additive effect in the value of some response. In the questions above, we explored the severity of COVID-19 (response) given variables age and medical condition. Do age and medical condition have an interaction effect in the severity of COVID-19?</em></p>
<pre class="r"><code>class(severity)</code></pre>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<pre class="r"><code>with(covid, interaction.plot(age_group, medcond_yn, severity))</code></pre>
<p><img src="CovidCases_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>The graph indicates this might be the case that age groups and pre-medical conditions do have an interactive effect with the risk of severe illness.</p>
</div>
<div id="your-question" class="section level2">
<h2>6 - Your Question</h2>
<p><em>Come up with your own question about COVID-19, and answer it using this data set. You may want to explore other demographic columns: sex, and race / ethnicity. You could also look at how the number of cases have changed over time using the report dates.</em></p>
<pre class="r"><code>covid$medical = as.numeric(covid$medcond_yn == &quot;Yes&quot;)
with(covid, interaction.plot(medical, sex, severity))</code></pre>
<p><img src="CovidCases_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>This graph includes the risk of severe illness as a response with given variables as pre-medical conditions and sex. The graph shows this might be the case that pre-medical conditions and sex do have an interactive effect with the risk of severe illness. In the case of missing, unknown, and others, it is inconclusive to interpret there is a shift.</p>
<p><br><br><br><br></p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
