<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Groceries Data</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/yeti.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 45px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 50px;
  margin-top: -50px;
}
.section h2 {
  padding-top: 50px;
  margin-top: -50px;
}
.section h3 {
  padding-top: 50px;
  margin-top: -50px;
}
.section h4 {
  padding-top: 50px;
  margin-top: -50px;
}
.section h5 {
  padding-top: 50px;
  margin-top: -50px;
}
.section h6 {
  padding-top: 50px;
  margin-top: -50px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Personal Page</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="QuinticPoly.html">Quintic Polynomials</a>
</li>
<li>
  <a href="CompTheoryLang.html">Computer Theory and Languages</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    R Samples
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="RandomVariables.html">Random Variables</a>
    </li>
    <li>
      <a href="IntroDataFrame.html">Intro to Data Frame</a>
    </li>
    <li>
      <a href="AnalyzingSimulations.html">Analyzing Simulations</a>
    </li>
    <li>
      <a href="PredictingFunction.html">Predicting Function</a>
    </li>
    <li>
      <a href="InterestRate.html">Interest Rate</a>
    </li>
    <li>
      <a href="CovidCases.html">Covid Cases</a>
    </li>
    <li>
      <a href="GroceriesProject.html">Groceries Data</a>
    </li>
  </ul>
</li>
<li>
  <a href="sqlSample.html">SQL Example</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Groceries Data</h1>

</div>


<div id="introduction" class="section level4">
<h4>Introduction</h4>
<p>The <a href="https://www.kaggle.com/heeraldedhia/groceries-dataset?select=Groceries_dataset.csv">data set</a> has 3 columns and 38765 rows of purchase orders from grocery stores. I choose this data since Market Basket Analysis is one of the techniques to see associations between items by looking for combinations of items being purchased together frequently. In this project, I want to learn about Association Rules to analyze transaction data.</p>
<p>Association rules are statements that help to find relationships between data.</p>
<p>An association rule has two parts, an antecedent and a consequent. An antecedent is an item found in the data. A consequent is an item that is found in combination with the antecedent. Association rules are created by analyzing data for frequent relationships and using support and confidence to identify the most important relationships. Support is an indication of how frequently the items being purchased. Confidence states the number of times the antecedent/consequent statements found. More detail on <a href="https://cran.r-project.org/web/packages/arules/vignettes/arules.pdf">arule</a>.</p>
</div>
<div id="outcomes" class="section level4">
<h4>Outcomes</h4>
<ul>
<li>Identifying items which are purchased more frequently</li>
<li>Identifying relationships between items purchased: support, lift, confidence</li>
<li>Data visualizations</li>
</ul>
</div>
<div id="loading-data" class="section level4">
<h4>Loading Data</h4>
<pre class="r"><code>library(&quot;plyr&quot;)
library(&quot;Matrix&quot;)
library(&quot;arules&quot;, warn.conflicts = FALSE)
library(&quot;grid&quot;)
library(&quot;arulesViz&quot;)
library(&quot;colorspace&quot;)

groceries = read.csv(&quot;C:/Users/kanni/Downloads/Groceries_dataset.csv&quot;)
class(groceries)</code></pre>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<pre class="r"><code>dim(groceries)</code></pre>
<pre><code>## [1] 38765     3</code></pre>
<pre class="r"><code>str(groceries)</code></pre>
<pre><code>## &#39;data.frame&#39;:    38765 obs. of  3 variables:
##  $ Member_number  : int  1808 2552 2300 1187 3037 4941 4501 3803 2762 4119 ...
##  $ Date           : chr  &quot;21-07-2015&quot; &quot;05-01-2015&quot; &quot;19-09-2015&quot; &quot;12-12-2015&quot; ...
##  $ itemDescription: chr  &quot;tropical fruit&quot; &quot;whole milk&quot; &quot;pip fruit&quot; &quot;other vegetables&quot; ...</code></pre>
<pre class="r"><code>head(groceries)</code></pre>
<pre><code>##   Member_number       Date  itemDescription
## 1          1808 21-07-2015   tropical fruit
## 2          2552 05-01-2015       whole milk
## 3          2300 19-09-2015        pip fruit
## 4          1187 12-12-2015 other vegetables
## 5          3037 01-02-2015       whole milk
## 6          4941 14-02-2015       rolls/buns</code></pre>
<pre class="r"><code># check for NA
sum(is.na(groceries))</code></pre>
<pre><code>## [1] 0</code></pre>
<pre class="r"><code># converting `Member_number`
sorting = groceries[order(groceries$Member_number),]
sorting$Member_number = as.numeric(sorting$Member_number)
str(sorting)</code></pre>
<pre><code>## &#39;data.frame&#39;:    38765 obs. of  3 variables:
##  $ Member_number  : num  1000 1000 1000 1000 1000 1000 1000 1000 1000 1000 ...
##  $ Date           : chr  &quot;27-05-2015&quot; &quot;24-07-2015&quot; &quot;15-03-2015&quot; &quot;25-11-2015&quot; ...
##  $ itemDescription: chr  &quot;soda&quot; &quot;canned beer&quot; &quot;sausage&quot; &quot;sausage&quot; ...</code></pre>
<pre class="r"><code># grouping same `Member_number` and `Date`
itemsList = ddply(sorting, c(&quot;Member_number&quot;, &quot;Date&quot;), function(df1) paste(df1$itemDescription, collapse = &quot;,&quot;))
head(itemsList, 10)</code></pre>
<pre><code>##    Member_number       Date                                            V1
## 1           1000 15-03-2015 sausage,whole milk,semi-finished bread,yogurt
## 2           1000 24-06-2014                 whole milk,pastry,salty snack
## 3           1000 24-07-2015                   canned beer,misc. beverages
## 4           1000 25-11-2015                      sausage,hygiene articles
## 5           1000 27-05-2015                       soda,pickled vegetables
## 6           1001 02-05-2015                              frankfurter,curd
## 7           1001 07-02-2014                 sausage,whole milk,rolls/buns
## 8           1001 12-12-2014                               whole milk,soda
## 9           1001 14-04-2015                              beef,white bread
## 10          1001 20-01-2015           frankfurter,soda,whipped/sour cream</code></pre>
<pre class="r"><code># setting `Member_number` and `Date` to NULL
itemsList$Member_number &lt;- NULL
itemsList$Date &lt;- NULL
colnames(itemsList) &lt;- c(&quot;itemsList&quot;)

# writing out itemsList
write.csv(itemsList,&quot;ItemsList.csv&quot;, quote = FALSE, row.names = TRUE)
head(itemsList)</code></pre>
<pre><code>##                                       itemsList
## 1 sausage,whole milk,semi-finished bread,yogurt
## 2                 whole milk,pastry,salty snack
## 3                   canned beer,misc. beverages
## 4                      sausage,hygiene articles
## 5                       soda,pickled vegetables
## 6                              frankfurter,curd</code></pre>
<pre class="r"><code># converting itemsList to basket type
basket = read.transactions(file=&quot;ItemsList.csv&quot;, rm.duplicates= TRUE, format=&quot;basket&quot;,sep=&quot;,&quot;,cols=1);</code></pre>
<pre><code>## distribution of transactions with duplicates:
## items
##   1   2   3   4 
## 662  39   5   1</code></pre>
<pre class="r"><code>print(basket)</code></pre>
<pre><code>## transactions in sparse format with
##  14964 transactions (rows) and
##  168 items (columns)</code></pre>
<pre class="r"><code># removing quotes
basket@itemInfo$labels = gsub(&quot;\&quot;&quot;,&quot;&quot;,basket@itemInfo$labels)

# displaying frequent items purchased
itemFrequencyPlot(basket,topN=20,type=&quot;absolute&quot;,main=&quot;Item Frequency&quot;)</code></pre>
<p><img src="GroceriesProject_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
</div>
<div id="rules" class="section level4">
<h4>Rules</h4>
<p>Support = Probability (A and B) Support = (# of transactions involving A and B) / (total # of transactions).</p>
<p>Confidence = Probability (A and B) = P(A) Confidence = (# of transactions involving A and B) / (total # of transactions that have A).</p>
<pre class="r"><code># using apriori algorithm to create rules
basketRules &lt;- apriori(basket, parameter = list(minlen=2, sup = 0.001, conf = 0.06, target=&quot;rules&quot;))</code></pre>
<pre><code>## Apriori
## 
## Parameter specification:
##  confidence minval smax arem  aval originalSupport maxtime support minlen
##        0.06    0.1    1 none FALSE            TRUE       5   0.001      2
##  maxlen target  ext
##      10  rules TRUE
## 
## Algorithmic control:
##  filter tree heap memopt load sort verbose
##     0.1 TRUE TRUE  FALSE TRUE    2    TRUE
## 
## Absolute minimum support count: 14 
## 
## set item appearances ...[0 item(s)] done [0.00s].
## set transactions ...[168 item(s), 14964 transaction(s)] done [0.01s].
## sorting and recoding items ... [149 item(s)] done [0.00s].
## creating transaction tree ... done [0.01s].
## checking subsets of size 1 2 3 4 done [0.00s].
## writing ... [361 rule(s)] done [0.00s].
## creating S4 object  ... done [0.00s].</code></pre>
<pre class="r"><code># print basketRules generated
print(length(basketRules))</code></pre>
<pre><code>## [1] 361</code></pre>
<pre class="r"><code>summary(basketRules)</code></pre>
<pre><code>## set of 361 rules
## 
## rule length distribution (lhs + rhs):sizes
##   2   3 
## 334  27 
## 
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   2.000   2.000   2.000   2.075   2.000   3.000 
## 
## summary of quality measures:
##     support           confidence         coverage             lift       
##  Min.   :0.001002   Min.   :0.06014   Min.   :0.005346   Min.   :0.5195  
##  1st Qu.:0.001337   1st Qu.:0.07473   1st Qu.:0.014836   1st Qu.:0.7575  
##  Median :0.001938   Median :0.08837   Median :0.021852   Median :0.8278  
##  Mean   :0.002856   Mean   :0.09562   Mean   :0.031359   Mean   :0.8883  
##  3rd Qu.:0.003408   3rd Qu.:0.11392   3rd Qu.:0.037757   3rd Qu.:0.9547  
##  Max.   :0.014836   Max.   :0.25581   Max.   :0.157912   Max.   :2.1831  
##      count       
##  Min.   : 15.00  
##  1st Qu.: 20.00  
##  Median : 29.00  
##  Mean   : 42.74  
##  3rd Qu.: 51.00  
##  Max.   :222.00  
## 
## mining info:
##    data ntransactions support confidence
##  basket         14964   0.001       0.06</code></pre>
<pre class="r"><code>inspect(basketRules[1:15])</code></pre>
<pre><code>##      lhs                            rhs                support     confidence
## [1]  {frozen fish}               =&gt; {whole milk}       0.001069233 0.1568627 
## [2]  {seasonal products}         =&gt; {rolls/buns}       0.001002406 0.1415094 
## [3]  {pot plants}                =&gt; {other vegetables} 0.001002406 0.1282051 
## [4]  {pot plants}                =&gt; {whole milk}       0.001002406 0.1282051 
## [5]  {pasta}                     =&gt; {whole milk}       0.001069233 0.1322314 
## [6]  {pickled vegetables}        =&gt; {whole milk}       0.001002406 0.1119403 
## [7]  {packaged fruit/vegetables} =&gt; {rolls/buns}       0.001202887 0.1417323 
## [8]  {detergent}                 =&gt; {yogurt}           0.001069233 0.1240310 
## [9]  {detergent}                 =&gt; {rolls/buns}       0.001002406 0.1162791 
## [10] {detergent}                 =&gt; {whole milk}       0.001403368 0.1627907 
## [11] {semi-finished bread}       =&gt; {other vegetables} 0.001002406 0.1056338 
## [12] {semi-finished bread}       =&gt; {whole milk}       0.001670676 0.1760563 
## [13] {red/blush wine}            =&gt; {rolls/buns}       0.001336541 0.1273885 
## [14] {red/blush wine}            =&gt; {other vegetables} 0.001136060 0.1082803 
## [15] {flour}                     =&gt; {tropical fruit}   0.001069233 0.1095890 
##      coverage    lift      count
## [1]  0.006816359 0.9933534 16   
## [2]  0.007083667 1.2864807 15   
## [3]  0.007818765 1.0500611 15   
## [4]  0.007818765 0.8118754 15   
## [5]  0.008086073 0.8373723 16   
## [6]  0.008954825 0.7088763 15   
## [7]  0.008487036 1.2885066 18   
## [8]  0.008620690 1.4443580 16   
## [9]  0.008620690 1.0571081 15   
## [10] 0.008620690 1.0308929 21   
## [11] 0.009489441 0.8651911 15   
## [12] 0.009489441 1.1148993 25   
## [13] 0.010491847 1.1581057 20   
## [14] 0.010491847 0.8868668 17   
## [15] 0.009756750 1.6172489 16</code></pre>
<pre class="r"><code># Rules visualization
plot(basketRules, jitter = 0)</code></pre>
<p><img src="GroceriesProject_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<pre class="r"><code># plotting first 40 rules
plot(basketRules[1:40], method=&quot;graph&quot;)</code></pre>
<p><img src="GroceriesProject_files/figure-html/unnamed-chunk-6-2.png" width="672" /></p>
<p><code>summary(basketRules)</code> shows there is total of 361 rules with mean support is equal to 0.28% and mean confidense is equal to 9.56% which states rule happens in 0.28% transactions and implication is 9.56%.</p>
</div>
<div id="correlation-lift" class="section level4">
<h4>Correlation/ Lift</h4>
<p>If lift = 1, then A and B are independent . If lift &gt; 1, then A and B are positively correlated . If lift &lt; 1, then A and B are negatively correlated.</p>
<p>Firstly let us try the eclat algorithm - to see most frequent itemsets. Below we will see the list of the most common items together with their individual support.</p>
<pre class="r"><code># use eclat to show most frequent items with support 
frequentSets &lt;- eclat(basket, parameter=list(supp=0.07, maxlen=10))</code></pre>
<pre><code>## Eclat
## 
## parameter specification:
##  tidLists support minlen maxlen            target  ext
##     FALSE    0.07      1     10 frequent itemsets TRUE
## 
## algorithmic control:
##  sparse sort verbose
##       7   -2    TRUE
## 
## Absolute minimum support count: 1047 
## 
## create itemset ... 
## set transactions ...[168 item(s), 14964 transaction(s)] done [0.01s].
## sorting and recoding items ... [5 item(s)] done [0.00s].
## creating sparse bit matrix ... [5 row(s), 14964 column(s)] done [0.00s].
## writing  ... [5 set(s)] done [0.00s].
## Creating S4 object  ... done [0.00s].</code></pre>
<pre class="r"><code>inspect(frequentSets)</code></pre>
<pre><code>##     items              support    transIdenticalToItemsets count
## [1] {whole milk}       0.15791232 2363                     2363 
## [2] {other vegetables} 0.12209302 1827                     1827 
## [3] {rolls/buns}       0.10999733 1646                     1646 
## [4] {soda}             0.09709971 1453                     1453 
## [5] {yogurt}           0.08587276 1285                     1285</code></pre>
<pre class="r"><code>sodaRules = subset(basketRules, items %in% &quot;soda&quot;)
inspect(head(sodaRules))</code></pre>
<pre><code>##     lhs                   rhs    support     confidence coverage   lift     
## [1] {chewing gum}      =&gt; {soda} 0.001002406 0.08333333 0.01202887 0.8582244
## [2] {specialty bar}    =&gt; {soda} 0.001269714 0.09090909 0.01396685 0.9362448
## [3] {hygiene articles} =&gt; {soda} 0.001069233 0.07804878 0.01369955 0.8038004
## [4] {candy}            =&gt; {soda} 0.001269714 0.08837209 0.01436782 0.9101170
## [5] {sliced cheese}    =&gt; {soda} 0.001136060 0.08095238 0.01403368 0.8337037
## [6] {ice cream}        =&gt; {soda} 0.001202887 0.07929515 0.01516974 0.8166364
##     count
## [1] 15   
## [2] 19   
## [3] 16   
## [4] 19   
## [5] 17   
## [6] 18</code></pre>
<pre class="r"><code>plot(sodaRules,method=&quot;graph&quot;,interactive=FALSE,shading=&quot;lift&quot;)</code></pre>
<pre><code>## Warning in plot.rules(sodaRules, method = &quot;graph&quot;, interactive = FALSE, : The
## parameter interactive is deprecated. Use engine=&#39;interactive&#39; instead.</code></pre>
<p><img src="GroceriesProject_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<pre class="r"><code>sausageRules = subset(basketRules, items %in% &quot;sausage&quot;)
inspect(head(sort(sausageRules, by =&quot;lift&quot;)))</code></pre>
<pre><code>##     lhs                     rhs          support     confidence coverage   
## [1] {whole milk,yogurt}  =&gt; {sausage}    0.001470195 0.13173653 0.011160118
## [2] {sausage,whole milk} =&gt; {yogurt}     0.001470195 0.16417910 0.008954825
## [3] {sausage,yogurt}     =&gt; {whole milk} 0.001470195 0.25581395 0.005747126
## [4] {beverages}          =&gt; {sausage}    0.001537022 0.09274194 0.016573109
## [5] {soda,whole milk}    =&gt; {sausage}    0.001069233 0.09195402 0.011627907
## [6] {curd}               =&gt; {sausage}    0.002940390 0.08730159 0.033680834
##     lift     count
## [1] 2.183062 22   
## [2] 1.911888 22   
## [3] 1.619975 22   
## [4] 1.536866 23   
## [5] 1.523810 16   
## [6] 1.446712 44</code></pre>
<pre class="r"><code>plot(sausageRules,method=&quot;graph&quot;,interactive=FALSE,shading=&quot;lift&quot;)</code></pre>
<pre><code>## Warning in plot.rules(sausageRules, method = &quot;graph&quot;, interactive = FALSE, : The
## parameter interactive is deprecated. Use engine=&#39;interactive&#39; instead.</code></pre>
<p><img src="GroceriesProject_files/figure-html/unnamed-chunk-8-2.png" width="672" /></p>
<p><code>sausageRules</code> can be interpreted as such:</p>
<ul>
<li>customers who buys whole milk and yogurt are more than two times, more likely to buy sausage than other customers.</li>
<li>customers who buys beverages are more than once, more likely to buy sausage than other customers.</li>
</ul>
</div>
<div id="more-visualizations" class="section level4">
<h4>More Visualizations</h4>
<p>Each of the matrix cells can have different red shade depending on the lift value. Numbers on the axes are corresponding to the items listed before the matrix. For instance, the most red cell corresponds to the rule {whole milk,yogurt} =&gt; {sausage}, so sausage is most likely to be bought with whole milk and yogurt.</p>
<pre class="r"><code>plot(sausageRules, method=&quot;matrix&quot;, measure=c(&quot;support&quot;,&quot;confidence&quot;))</code></pre>
<pre><code>## Itemsets in Antecedent (LHS)
##  [1] &quot;{whole milk,yogurt}&quot;     &quot;{sausage,yogurt}&quot;       
##  [3] &quot;{beverages}&quot;             &quot;{soda,whole milk}&quot;      
##  [5] &quot;{curd}&quot;                  &quot;{sausage,whole milk}&quot;   
##  [7] &quot;{rolls/buns,whole milk}&quot; &quot;{rolls/buns,sausage}&quot;   
##  [9] &quot;{sliced cheese}&quot;         &quot;{frozen meals}&quot;         
## [11] &quot;{grapes}&quot;                &quot;{frozen vegetables}&quot;    
## [13] &quot;{bottled beer}&quot;          &quot;{sausage,soda}&quot;         
## [15] &quot;{misc. beverages}&quot;       &quot;{yogurt}&quot;               
## [17] &quot;{dessert}&quot;               &quot;{pastry}&quot;               
## [19] &quot;{soda}&quot;                  &quot;{salty snack}&quot;          
## [21] &quot;{sausage}&quot;              
## Itemsets in Consequent (RHS)
## [1] &quot;{other vegetables}&quot; &quot;{rolls/buns}&quot;       &quot;{soda}&quot;            
## [4] &quot;{whole milk}&quot;       &quot;{sausage}&quot;          &quot;{yogurt}&quot;</code></pre>
<p><img src="GroceriesProject_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<pre class="r"><code>plot(sausageRules, method=&quot;grouped&quot;, measure=&quot;support&quot;, control=list(col=sequential_hcl(100)))</code></pre>
<p><img src="GroceriesProject_files/figure-html/unnamed-chunk-9-2.png" width="672" /></p>
<p>Grouped matrix plot has the same data on the axes. Yet, the size reflects the support of the rule and the color reflects the lift of the rule.</p>
<pre class="r"><code>inspect(head(sort(basketRules, by = &quot;lift&quot;)))</code></pre>
<pre><code>##     lhs                      rhs              support     confidence
## [1] {whole milk,yogurt}   =&gt; {sausage}        0.001470195 0.13173653
## [2] {sausage,whole milk}  =&gt; {yogurt}         0.001470195 0.16417910
## [3] {specialty chocolate} =&gt; {citrus fruit}   0.001403368 0.08786611
## [4] {sausage,yogurt}      =&gt; {whole milk}     0.001470195 0.25581395
## [5] {flour}               =&gt; {tropical fruit} 0.001069233 0.10958904
## [6] {beverages}           =&gt; {sausage}        0.001537022 0.09274194
##     coverage    lift     count
## [1] 0.011160118 2.183062 22   
## [2] 0.008954825 1.911888 22   
## [3] 0.015971665 1.653872 21   
## [4] 0.005747126 1.619975 22   
## [5] 0.009756750 1.617249 16   
## [6] 0.016573109 1.536866 23</code></pre>
<pre class="r"><code>inspect(tail(sort(basketRules, by = &quot;lift&quot;)))</code></pre>
<pre><code>##     lhs                           rhs                support     confidence
## [1] {butter milk}              =&gt; {other vegetables} 0.001269714 0.07224335
## [2] {sugar}                    =&gt; {other vegetables} 0.001269714 0.07169811
## [3] {pastry}                   =&gt; {other vegetables} 0.003675488 0.07105943
## [4] {misc. beverages}          =&gt; {whole milk}       0.001403368 0.08898305
## [5] {specialty chocolate}      =&gt; {whole milk}       0.001336541 0.08368201
## [6] {long life bakery product} =&gt; {other vegetables} 0.001136060 0.06343284
##     coverage   lift      count
## [1] 0.01757551 0.5917074 19   
## [2] 0.01770917 0.5872417 19   
## [3] 0.05172414 0.5820106 55   
## [4] 0.01577118 0.5634966 21   
## [5] 0.01597167 0.5299270 20   
## [6] 0.01790965 0.5195451 17</code></pre>
<p>According to this <code>basketRule</code>, the highest lift value is 2.18 which means that customers are most likely to buy sausage than any other product, while already having whole milk and yogurt in basket. The lowest lift value is 0.519 which means that customers are least likely to buy other vegetables than any other product, while already having long life bakery product in basket.</p>
<p><br><br><br><br></p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
